name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: pwd && ls -ltr && rm -rf ./node_modules && node --version && npm install --legacy-peer-deps && firebase use evlotime--dev
      # - uses: kburakengin/firebase-functions-deploy@v1.2
      #   with:
      #     serviceAccountKey: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVLOTIME__DEV }}"
      #     projectId: "evlotime--dev" 

      - uses: dheshalj/deploy-firebase-functions@v0.0.4
        env:
          FIREBASE_TOKEN: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVLOTIME__DEV }}"
          FIREBASE_PROJECT: "evlotime--dev" 