name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: cd functions && pwd && ls -ltr && rm -rf ./node_modules && node --version && npm install --legacy-peer-deps && npm install -g firebase-tools
      # - uses: kburakengin/firebase-functions-deploy@v1.2
      #   with:
      #     serviceAccountKey: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVLOTIME__DEV }}"
      #     projectId: "evlotime--dev" 

      # - uses: dheshalj/deploy-firebase-functions@v0.0.4
      #   env:
      #     FIREBASE_TOKEN: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVLOTIME__DEV }}"
      #     FIREBASE_PROJECT: "evlotime--dev" 

      # - uses: jsryudev/deploy-firebase-functions@v20.0.1
      #   env:
      #     FIREBASE_TOKEN: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVLOTIME__DEV }}"
      #     FIREBASE_PROJECT: "evlotime--dev" 


      - name: Download deps
        working-directory: functions
        run: npm install

      - name: Deploy
        run: firebase use evlotime--dev && npx firebase-tools deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVLOTIME__DEV }}